version: "3.9"

services:
  graphql:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - json-api
    environment:
      - BASE_URL=http://json-api:80
    volumes:
      - .:/app
    restart: always

  json-api:
    image: clue/json-server
    ports:
      - "3001:80"
    volumes:
      - ./db.json:/data/db.json
    command: -H 0.0.0.0 /data/db.json
